version: '3.1'

services:
  urlshortener:
    depends_on:
      - url-db
    build:
      context: .
    environment:
      DB_USERNAME: 12345
      DB_PASSWORD: 12345
    restart: always
  url-db:
    image: postgres:14.5
    restart: always
    environment:
      POSTGRES_USER: '12345'
      POSTGRES_PASSWORD: '12345'
      POSTGRES_DB: 'urlshortener'
    ports:
      - '5432:5432'
    expose:
      - '5432'
    command: --character-set-server=utf8 --collation-server=utf8_general_ci